# Generated by Django 5.2.14 on 2026-06-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Size')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Số nhỏ hơn hiển thị trước (35 → 0, 35.5 → 1, 36 → 2...)', verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Size',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Màu sắc', 'verbose_name_plural': 'Màu sắc'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size__order', 'size__name'], 'verbose_name': 'Biến thể', 'verbose_name_plural': 'Biến thể'},
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color', verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Ảnh riêng'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá (để trống = theo sản phẩm)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.size', verbose_name='Size'),
        ),
    ]
