# Generated by Django 5.2.14 on 2026-06-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_size_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'color', 'order'], 'verbose_name': 'Hình ảnh sản phẩm', 'verbose_name_plural': 'Hình ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Kích thước', 'verbose_name_plural': 'Kích thước'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Gắn ảnh với màu cụ thể. Để trống = ảnh chung cho tất cả màu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='products.color', verbose_name='Màu sắc'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Số nhỏ hiển thị trước', verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Ảnh hiển thị khi không chọn màu cụ thể', verbose_name='Ảnh đại diện'),
        ),
    ]
