# Generated by Django 5.2.14 on 2026-06-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_color_order_to_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Nhập kho'), ('out', 'Xuất kho (bán)'), ('adjust', 'Điều chỉnh'), ('return', 'Trả hàng'), ('cancel', 'Huỷ đặt giữ')], max_length=10, verbose_name='Loại')),
                ('quantity', models.IntegerField(help_text='Số dương = nhập vào, số âm = xuất ra', verbose_name='Số lượng')),
                ('stock_before', models.PositiveIntegerField(verbose_name='Tồn trước')),
                ('stock_after', models.PositiveIntegerField(verbose_name='Tồn sau')),
                ('order_code', models.CharField(blank=True, max_length=32, verbose_name='Mã đơn hàng')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Thực hiện bởi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.productvariant', verbose_name='Biến thể')),
            ],
            options={
                'verbose_name': 'Lịch sử tồn kho',
                'verbose_name_plural': 'Lịch sử tồn kho',
                'ordering': ['-created_at'],
            },
        ),
    ]
