# Generated by Django 5.2.14 on 2026-06-26 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_stock_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Mã đợt')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('sent', 'Đã gửi NCC'), ('quoted', 'Đã nhận báo giá'), ('approved', 'Đã duyệt'), ('receiving', 'Đang nhận hàng'), ('done', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Đợt mua hàng',
                'verbose_name_plural': 'Đợt mua hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ báo giá'), ('submitted', 'Đã nộp báo giá'), ('approved', 'Đã duyệt'), ('rejected', 'Không chọn')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='quotes/', verbose_name='File báo giá (CSV)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú từ NCC')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nộp')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='products.purchaserequest', verbose_name='Đợt mua hàng')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='products.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Báo giá NCC',
                'verbose_name_plural': 'Báo giá NCC',
                'ordering': ['-created_at'],
                'unique_together': {('request', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.PositiveIntegerField(default=1, verbose_name='Số lượng yêu cầu')),
                ('qty_received', models.PositiveIntegerField(default=0, verbose_name='Số lượng thực nhận')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaserequest')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='products.productvariant', verbose_name='Biến thể')),
            ],
            options={
                'verbose_name': 'Chi tiết đợt mua',
                'verbose_name_plural': 'Chi tiết đợt mua',
                'unique_together': {('request', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá báo')),
                ('qty_available', models.PositiveIntegerField(default=0, verbose_name='Kho NCC còn')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='products.quotesubmission')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='products.productvariant', verbose_name='Biến thể')),
            ],
            options={
                'verbose_name': 'Chi tiết báo giá',
                'verbose_name_plural': 'Chi tiết báo giá',
                'unique_together': {('submission', 'variant')},
            },
        ),
    ]
