# Generated by Django 5.2.14 on 2026-06-27 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_stock_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên NCC')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đăng nhập NCC')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(default='Đợt thu mua bổ sung tồn kho', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('sent', 'Đã gửi NCC'), ('quoted', 'NCC đã báo giá'), ('approved', 'Đã duyệt NCC'), ('received', 'Đã nhận hàng'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Hạn báo giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='products.supplier', verbose_name='NCC được chọn')),
                ('suppliers', models.ManyToManyField(blank=True, to='products.supplier', verbose_name='Gửi đến NCC')),
            ],
            options={
                'verbose_name': 'Đợt yêu cầu đặt hàng',
                'verbose_name_plural': 'Đợt yêu cầu đặt hàng',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_purchase', 'Có thể duyệt đặt hàng'), ('can_receive_goods', 'Có thể nhận hàng')],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú từ NCC')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='supplier_quotes/', verbose_name='File CSV báo giá')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='products.purchaserequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
            options={
                'verbose_name': 'Báo giá NCC',
                'verbose_name_plural': 'Báo giá NCC',
                'unique_together': {('request', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Tồn lúc tạo')),
                ('requested_qty', models.PositiveIntegerField(verbose_name='SL yêu cầu')),
                ('received_qty', models.PositiveIntegerField(default=0, verbose_name='SL thực nhận')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaserequest')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Chi tiết yêu cầu',
                'unique_together': {('request', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('available_qty', models.PositiveIntegerField(default=0)),
                ('lead_days', models.PositiveSmallIntegerField(default=3)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.supplierquote')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'unique_together': {('quote', 'variant')},
            },
        ),
    ]
