# Generated by Django 5.2.14 on 2026-07-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_inventory_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestitem',
            options={'verbose_name': 'Chi tiết yêu cầu', 'verbose_name_plural': 'Chi tiết yêu cầu'},
        ),
    ]
