# Generated by Django 5.2.14 on 2026-07-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Tên tài khoản')),
                ('user_role', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('action', models.CharField(max_length=100, verbose_name='Hành động')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='Đối tượng tác động')),
                ('changes', models.TextField(blank=True, verbose_name='Nội dung thay đổi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lịch sử hoạt động',
                'verbose_name_plural': 'Lịch sử hoạt động',
                'ordering': ['-created_at'],
            },
        ),
    ]
