# Generated by Django 5.2.14 on 2026-06-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã voucher')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định (₫)')], default='fixed', max_length=10, verbose_name='Loại giảm')),
                ('discount_value', models.DecimalField(decimal_places=0, help_text='VD: 35000 (cố định) hoặc 10 (10%)', max_digits=12, verbose_name='Giá trị giảm')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn tối thiểu (₫)')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, help_text='Chỉ áp dụng cho loại phần trăm. Để trống = không giới hạn.', max_digits=12, null=True, verbose_name='Giảm tối đa (₫)')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Để trống = không giới hạn', null=True, verbose_name='Giới hạn lượt dùng')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Đã dùng')),
                ('valid_from', models.DateTimeField(verbose_name='Hiệu lực từ')),
                ('valid_to', models.DateTimeField(verbose_name='Hết hạn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Voucher',
                'ordering': ['-valid_to'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền giảm'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã voucher (lưu lại)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.voucher', verbose_name='Voucher'),
        ),
    ]
