# Generated by Django 5.2.14 on 2026-06-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_add_voucher_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-valid_to'], 'verbose_name': 'Phiếu giảm giá', 'verbose_name_plural': 'Phiếu giảm giá'},
        ),
    ]
