# Generated by Django 5.2.14 on 2026-06-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_add_variant_to_cartitem'),
        ('products', '0004_add_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant', verbose_name='Biến thể (size/màu)'),
        ),
    ]
