# Generated by Django 5.2.14 on 2026-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_add_variant_to_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sepay_ipn_payload',
            field=models.TextField(blank=True, verbose_name='SePay IPN payload'),
        ),
        migrations.AddField(
            model_name='order',
            name='sepay_order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='SePay Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='sepay_trans_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='SePay Transaction ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'MoMo'), ('sepay', 'SePay'), ('cod', 'COD')], default='momo', max_length=20),
        ),
    ]
