# Generated by Django 5.2.14 on 2026-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_add_sepay_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sepay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sepay_trans_id',
        ),
        migrations.AddField(
            model_name='order',
            name='sepay_invoice_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='SePay invoice number'),
        ),
        migrations.AddField(
            model_name='order',
            name='sepay_pay_url',
            field=models.URLField(blank=True, verbose_name='SePay checkout URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='sepay_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='SePay order status'),
        ),
        migrations.AddField(
            model_name='order',
            name='sepay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SePay transaction ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sepay_ipn_payload',
            field=models.TextField(blank=True, verbose_name='SePay IPN raw payload'),
        ),
    ]
