# Generated by Django 5.2.14 on 2026-06-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_add_sepay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nhận hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed',
            field=models.BooleanField(default=False, verbose_name='Đã xác nhận nhận hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('failed', 'Thanh toán thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định (₫)')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị giảm'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_to',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('failed', 'Thanh toán thất bại'), ('cancelled', 'Đã hủy')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Thực hiện bởi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cart.order')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'ordering': ['created_at'],
            },
        ),
    ]
