# Generated by Django 5.2.14 on 2026-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_add_delivery_status_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'Mới tạo'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='new', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('failed', 'Thanh toán thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái (legacy)'),
        ),
    ]
